---
title: "R Notebook"
output: html_notebook
---

```{r load_packages}
library(tidyverse)
library(tidymodels)
library(kknn)
library(tidytext)
library(textrecipes)
library(here)
library(moderndive)
library(ranger)
library(recipes)
library(rsample)
library(caret)
```


```{r set_style}
theme_set(theme_minimal())
scotblue <- "#0065BF"
ukred <- "#D00C27"
```


```{r load_data}
data <- read_csv('Data/Data.csv', show_col_types = FALSE)
```
```{r split conll and acl}
data_acl <- data %>% filter(conference == 'acl_2017')
data_conll <- data %>% filter(conference == 'conll_2016')
```


```{r split_all}
set.seed(1234)
data_splot <- initial_split(data, strata = RECOMMENDATION)
train_all <- training(data_splot)
test_all  <- testing(data_splot)
```


```{r set_linear_model}
RECOMMENDATION_all_model <- lm(RECOMMENDATION ~ IMPACT+SUBSTANCE+APPROPRIATENESS+MEANINGFUL_COMPARISON+SOUNDNESS_CORRECTNESS+
ORIGINALITY+CLARITY+REVIEWER_CONFIDENCE,data = train)

```

```{r set_linear_model}
model_points

```

```{r}
model_points <- get_regression_points(RECOMMENDATION_all_model)
ggplot(score_model_points, aes(x = RECOMMENDATION_hat)) +
geom_histogram(bins = 20,color = "#000000", fill = "#0099F8") +
  labs(
    title = "Histogram of Recomndation Predicton of the linear model",
    subtitle = "linear model for both confrences",
    x = "Recomndation Predicton",
    y = "Count"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(color = "#0099F8", size = 16, face = "bold"),
    plot.subtitle = element_text(size = 10, face = "bold"),
    plot.caption = element_text(face = "italic")
  )
```


```{r}
model_points <- get_regression_points(RECOMMENDATION_all_model)
ggplot(model_points, aes(x = residual)) +
geom_histogram(bins = 50,color = "#000000", fill = "#0099F8") +
  labs(
    title = "Histogram of Recommendation Predicton of the linear model",
    x = "Recommendation Prediction Error",
    y = "Count"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(color = "#0099F8", size = 16, face = "bold"),
    plot.subtitle = element_text(size = 10, face = "bold"),
    plot.caption = element_text(face = "italic")
  )
```

```{r split_acl}
set.seed(1234)
data_split <- initial_split(data_acl, strata = RECOMMENDATION)
train_acl <- training(data_split)
test_acl  <- testing(data_split)
```


```{r split_conll}
set.seed(1234)
data_split <- initial_split(data_conll, strata = RECOMMENDATION)
train_conll <- training(data_split)
test_conll  <- testing(data_split)
```


```{r set_linear_model_acl}
RECOMMENDATION_acl_model <- lm(RECOMMENDATION ~ IMPACT+SUBSTANCE+APPROPRIATENESS+MEANINGFUL_COMPARISON+SOUNDNESS_CORRECTNESS+
ORIGINALITY+CLARITY+REVIEWER_CONFIDENCE
 ,data = train_acl)
RECOMMENDATION_acl_model
```



```{r histogram_acl}
RECOMMENDATION_model_points <- get_regression_points(RECOMMENDATION_acl_model)

model_points <- get_regression_points(RECOMMENDATION_model)
ggplot(model_points, aes(x = RECOMMENDATION_hat)) +
  geom_histogram(bins = 20) +
  labs(x = "Residual", y = "Count")
```


```{r}
ggplot(RECOMMENDATION_model_points, aes(x = SUBSTANCE, y = residual)) +
  geom_point() +
  labs(x = "SUBSTANCE", y = "RECOMMENDATION_hat")
```

```{r set_linear_model_conll}
RECOMMENDATION_conll_model <- lm(RECOMMENDATION ~ IMPACT+SUBSTANCE+APPROPRIATENESS+MEANINGFUL_COMPARISON+SOUNDNESS_CORRECTNESS+
ORIGINALITY+CLARITY+REVIEWER_CONFIDENCE
 ,data = train_conll)
RECOMMENDATION_conll_model

```
```{r histogram_conll}
model_points <- get_regression_points(RECOMMENDATION_conll_model)
ggplot(model_points, aes(x = RECOMMENDATION_hat)) +
  geom_histogram(bins = 20) +
  labs(x = "Residual", y = "Count")
```


```{r}
ggplot(model_points, aes(x = SUBSTANCE, y = residual)) +
  geom_point() +
  labs(x = "SUBSTANCE", y = "RECOMMENDATION_hat")
```




//Random Forest

```{r}
rf_mod <- rand_forest(mode="classification") %>%
  fit(as.factor(RECOMMENDATION) ~ IMPACT+SUBSTANCE+APPROPRIATENESS+MEANINGFUL_COMPARISON+SOUNDNESS_CORRECTNESS+
ORIGINALITY+CLARITY+REVIEWER_CONFIDENCE, train_all)


pred <- rf_mod %>% predict(test_all) %>% bind_cols(test_all %>% select(RECOMMENDATION))

pred
```




